{application,twig,
             [{description,"Logger"},
              {vsn,"0.2.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{twig_app,[]}},
              {env,[]},
              {modules,[trunc_io,twig,twig_app,twig_event_handler,
                        twig_monitor,twig_sup,twig_util]}]}.
